### ISSUE TITLE
Create a generic core app that supports user configurability

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-client-tbr#1]
Create a generic core android library module that supports user configurability. There should be zero coding required to modify anything on mobile application. App should be a folder with resoures, fonts, drawables, strings and should allow following

- [ ] #2 User configurable Forms
- [ ] #3 User configurable Home
- [ ] #4 User configurable Datagrid
- [ ] #5 User configurable Detail View
- [ ] #6 User configurable settings/preferences

**Comment by cagulas** [comment]
@maimoonak Closing this, since new issues were created for implementation that I think duplicate these. Please reopen if needed.
