### ISSUE TITLE
User configurable forms

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-client-tbr#2]
Th application should be integrated with ODK form renderer to allow app render data collection form dynamically.

- [ ] Add odk form renderer as library. opensrp/form-render#3
- [ ] Use opensrp server to get xforms
- [ ] Import odk form settings from server
- [ ] Allow opening form with preload data opensrp/form-render#4 and opensrp/form-render#5
- [ ] Submit form for given entity and dislay data referencing the record from json form submission. opensrp/form-render#6
- [ ] Allow parsing form into CE model. opensrp/form-render#7

**Comment by cagulas** [comment]
@maimoonak Closing this, since new issues were created for implementation that I think duplicate these. Please reopen if needed.
