### ISSUE TITLE
Update Results (Pres & Pos) configurable column

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#54]
I think it would be helpful to show several different options for Results (Presumptive & Positive only) in the configurable column, because I think there might be a spacing issue, so hopefully you can tell us.

First of all, can only three results be shown in the column? So, if there are four results, one gets bumped off based on the priority you listed?

- [ ] See https://github.com/OpenSRP/opensrp-client-tbr/issues/52 for Xpert result options. Would there still be room to show the error code or "No Result", or would these need to be abbreviated?
- [ ] See https://github.com/OpenSRP/opensrp-client-tbr/issues/53 for Smear result options. I think here we would need to abbreviate Scanty and Negative.
- [ ] See https://github.com/OpenSRP/opensrp-client-tbr/issues/34#issuecomment-346312569 for Xray result abbreviations.
- [ ] Culture result is only positive or negative, so would only be "Pos" or "Neg"

**Comment by cagulas** [comment]
Closing this issue. More info is provided in the issues mentioned in the first comment.
